package filmes_e_series;

public enum Categorias {
    TOP10, MARATONAR, MARATONAR_NO_FINAL_DE_SEMANA, ASSISTIR_COM_O_AMORECO, EM_FAMILIA, ESPECIAL_DE_NATAL, ESPECIAL_DIA_DAS_CRIANCAS, ESPECIAL_DIA_DOS_PAIS,
    ESPECIAL_DIA_DAS_MAES, TEEN, APIMENTADOS;
}
